#! /bin/tcsh -f

killall FullSimu2.PVDIS_4mm.TestFile4_Run.exe
killall FullSimu2.PVDIS_4mm.TestFile4_RunPi.exe
killall FullSimu2.PVDIS_5mm.TestFile4_Run.exe
killall FullSimu2.PVDIS_5mm.TestFile4_RunPi.exe
killall FullSimu2.PVDIS_6mm.TestFile4_Run.exe
killall FullSimu2.PVDIS_6mm.TestFile4_RunPi.exe
killall FullSimu2.PVDIS_8mm.TestFile4_Run.exe
killall FullSimu2.PVDIS_8mm.TestFile4_RunPi.exe
killall FullSimu2.SIDIS_Forward_4mm.SIDIS_Forward_Run.exe
killall FullSimu2.SIDIS_Forward_4mm.SIDIS_Forward_RunPi.exe
killall FullSimu2.SIDIS_Forward_5mm.SIDIS_Forward_Run.exe
killall FullSimu2.SIDIS_Forward_5mm.SIDIS_Forward_RunPi.exe
killall FullSimu2.SIDIS_Forward_6mm.SIDIS_Forward_Run.exe
killall FullSimu2.SIDIS_Forward_6mm.SIDIS_Forward_RunPi.exe
killall FullSimu2.SIDIS_Forward_8mm.SIDIS_Forward_Run.exe
killall FullSimu2.SIDIS_Forward_8mm.SIDIS_Forward_RunPi.exe
killall FullSimu2.SIDIS_Large_4mm.SIDIS_Large_Run.exe
killall FullSimu2.SIDIS_Large_4mm.SIDIS_Large_RunPi.exe
killall FullSimu2.SIDIS_Large_5mm.SIDIS_Large_Run.exe
killall FullSimu2.SIDIS_Large_5mm.SIDIS_Large_RunPi.exe
killall FullSimu2.SIDIS_Large_6mm.SIDIS_Large_Run.exe
killall FullSimu2.SIDIS_Large_6mm.SIDIS_Large_RunPi.exe
killall FullSimu2.SIDIS_Large_8mm.SIDIS_Large_Run.exe
killall FullSimu2.SIDIS_Large_8mm.SIDIS_Large_RunPi.exe
